# Generated by Django 4.2.15 on 2024-09-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reasons',
            field=models.TextField(null=True),
        ),
    ]
