# Generated by Django 4.2.15 on 2024-09-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
